[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#00c73c" # 네이버의 시그니처 그린 테마 색상
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"
font = "sans serif"
